### ISSUE TITLE
problema con linux backtrack 5 r3

### ISSUE THREAD

**Issue by sicuro85** [Pirate-Crew/IPTV#18]
Salve,
ci siamo sentiti via mail e finalmente riesco a scrivere qua.
utilizzo backtrack 5 r3
provo a utilizzare il vostro python ma non riesco.
faccio cosi:
apro il terminale
e metto:
git clone git@github.com:Pinperepette/IPTV.git
e mi restituisce questo
Initialized empty Git repository in /root/IPTV/.git/
Permission denied (publickey).
fatal: The remote end hung up unexpectedly
primo errore

**Comment by sicuro85** [comment]
allora provo con
git clone https://github.com/Pinperepette/IPTVInitialized 
e mi ritrovo la cartella iptv su root
poi proseguo cosi,

root@bt:~/IPTV-master/iptv# python iptv.py
Traceback (most recent call last):
  File "iptv.py", line 2, in <module>
    import Crawler
  File "/root/IPTV-master/iptv/Crawler.py", line 2, in <module>
    import google
ImportError: No module named google

dove sbaglio????

**Comment by sicuro85** [comment]
altra prova che faccio sempre da terminale è questa:

oot@bt:~# cd IPTV
root@bt:~/IPTV# cd iptv
root@bt:~/IPTV/iptv# pip install -r requirements.txt
The program 'pip' can be found in the following packages:
 * pip (You will have to enable component called 'universe')
 * python-pip (You will have to enable component called 'universe')
Try: apt-get install <selected package>
root@bt:~/IPTV/iptv#

**Comment by sicuro85** [comment]
posso lavorare anche su osx se mi aiutate vorrei aprire il programma con gui dallo screen shoot si vede la gui su osx

**Comment by Pinperepette** [comment]
devi installare i moduli, usa pip, è scritto tutto nel file readme :)

**Comment by sicuro85** [comment]
mi spiegheresti come fare??' non ci riesco sono nuovo.

**Comment by sicuro85** [comment]
ci provo ma mi restituisce questo:
root@bt:~# sudo apt-get install pyqt4-dev-tools
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  pyqt4-dev-tools
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 93.4kB of archives.
After this operation, 270kB of additional disk space will be used.
Err http://64.repository.backtrack-linux.org/ revolution/main pyqt4-dev-tools 4.7.3-1ubuntu2~lucid1~ppa3
  Something wicked happened resolving '64.repository.backtrack-linux.org:http' (-5 - No address associated with hostname)
Err http://updates.repository.backtrack-linux.org/ revolution/main pyqt4-dev-tools 4.7.3-1ubuntu2~lucid1~ppa3
  Something wicked happened resolving 'updates.repository.backtrack-linux.org:http' (-5 - No address associated with hostname)
Failed to fetch http://updates.repository.backtrack-linux.org/pool/main/p/python-qt4/pyqt4-dev-tools_4.7.3-1ubuntu2~lucid1~ppa3_amd64.deb  Something wicked happened resolving 'updates.repository.backtrack-linux.org:http' (-5 - No address associated with hostname)
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by sicuro85** [comment]
Siccome sono nuovo nn li so installa me lo potresti spiegare passo passo??

Inviato da iPad

**Comment by Pinperepette** [comment]
quello è un repository di backtrack, probabilmente hanno aggiunto questo tool mettendo come dipendenza (giustamente) le qt (da ciò presumo abbiano aggiunto la gui)... hanno usato questo sorgente, ma noi non centriamo con quel repo o con arch

**Comment by sicuro85** [comment]
avevo scritto un'altro post ma forse è meglio continure qua riesco ad entrare adesso con cli perchè il file con gui mi dice che non esiste, però dopo aver prumuto 1 e aver ricevuto la lista server quando scelgo il brute force mi dice sempre:
No results for http...........
e poi, si può attaccare un server di cui so l'indirizzo???

**Comment by ludo237** [comment]
reference: #19

**Comment by qwerty159** [comment]
Hai installato tutti i moduli?

**Comment by sicuro85** [comment]
A quali ti riferisci?

**Comment by qwerty159** [comment]
Quelli contenuti nel file di testo requirements.

**Comment by sicuro85** [comment]
li installo aprendo il file crawler...o con il pip..... provato in tutti e due i metodi

**Comment by ludo237** [comment]
Che output ti da `pip install -r requirements.txt` ?
