### ISSUE TITLE
HTTP Error 503: Service Unavailable

### ISSUE THREAD

**Issue by pietromalerba** [Pirate-Crew/IPTV#22]
Ciao, innanzitutto complimenti per il sw!
L'ho installato su un server ubuntu con python2.7

Dopo aver lanciato la ricerca ottengo

Please select an option: 1
Fetching URLs plase wait...
Traceback (most recent call last):
  File "iptv.py", line 37, in <module>
    cr.search_links()
  File "/root/IPTV/iptv/Crawler.py", line 59, in search_links
    for url in google.search(self.searchString, num=30, stop=1):
  File "/usr/local/lib/python2.7/dist-packages/google/__init__.py", line 269, in search
    html = get_page(url)
  File "/usr/local/lib/python2.7/dist-packages/google/__init__.py", line 89, in get_page
    response = urlopen(request)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 442, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 629, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 503: Service Unavailable

**Comment by ludo237** [comment]
Stai usando la stable, master branch, giusto?

**Comment by pietromalerba** [comment]
ciao si, master

**Comment by ludo237** [comment]
@pietromalerba il problema è sulla libreria urllib2, alcuni server fanno reject automatico della richiesta perchè vedono che non è un browser, devo sostituire la libreria con una più intelligente e fare un mockup della richiesta via browser. Ho identificato il problema e verrà sistemato ASAP.

**Comment by pietromalerba** [comment]
Ciao, ho aggiornato il repository e l'errore c'è sempre 
urllib2.HTTPError: HTTP Error 503: Service Unavailable
Sbaglio qualcosa?

**Comment by ludo237** [comment]
Molto strano la versione stabile non mi da problemi su macchina di test, screenshot perfavore

**Comment by pietromalerba** [comment]
https://www.dropbox.com/s/3eipxgegtf7s9ax/Screenshot%202016-01-14%2020.26.18.png?dl=0 
Sono su Ubuntu 14.04.3 LTS

**Comment by ludo237** [comment]
Visto lo screenshot, non riesco a riprodurre il bug. Sto provando con Debian e riesco a fetchare i link tranquillamente. Appena ho un po di tempo libero metto su ubuntu e vedo.

**Comment by txt3rob** [comment]
Ubuntu 16.04 - same issue

```
python iptv.py

################
##### IPTV #####
##### v1.2.3 ###
################

Menu
0 - Exit
1 - Search for some Servers
2 - Look at the servers list
3 - Select language, default is Italian
4 - Brute force all server from the list
5 - Brute force random server from the list
6 - Brute force specific server from the list
7 - Provide a random server to attack

Please select an option: 1
Fetching URLs plase wait...
Traceback (most recent call last):
  File "iptv.py", line 39, in <module>
    cr.search_links()
  File "/home/Rob/IPTV/iptv/Crawler.py", line 62, in search_links
    for url in google.search(self.searchString, num=30, stop=1):
  File "/usr/local/lib/python2.7/dist-packages/google/__init__.py", line 269, in                            search
    html = get_page(url)
  File "/usr/local/lib/python2.7/dist-packages/google/__init__.py", line 89, in                            get_page
    response = urlopen(request)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 503: Service Unavailable

```
