### ISSUE TITLE
Errore con la dev..potete aiutarmi?

### ISSUE THREAD

**Issue by BArdokk** [Pirate-Crew/IPTV#38]
Select an option: 
Traceback (most recent call last):
  File "iptv.py", line 192, in <module>
    menu()
  File "iptv.py", line 141, in menu
    menu()
  File "iptv.py", line 137, in menu
    selection = input("Select an option: ")
  File "<string>", line 1
    
        ^
SyntaxError: invalid syntax

**Comment by pikomule** [comment]
I have the same problem: line 192, 145 and 141

With option 5, you can scan an ip and when a list is detected, it downloads and stops scanning causing an error
