### ISSUE TITLE
File "iptv.py", line 53, in <module>

### ISSUE THREAD

**Issue by andykimpe** [Pirate-Crew/IPTV#43]
Traceback (most recent call last):
  File "iptv.py", line 53, in <module>
    url = cr.parsedUrls[i]
IndexError: list index out of range

**Comment by islamouahouda** [comment]
yes I have the same problem

**Comment by ooz120** [comment]
The same problem here too

**Comment by Delfioh** [comment]
WHAT PART OF [DEPRECATED] YOU DON'T UNDERSTAND

**Comment by ooz120** [comment]
Can't run iptv.py says that line 14 is missing, just written print"" in iptv.py
