### ISSUE TITLE
Error Module and Language

### ISSUE THREAD

**Issue by Ludotech** [Pirate-Crew/IPTV#46]
Hello i have this error with Dev versione

```
C:\Users\Ludo\Desktop\IPTV-dev-dev\iptv>python iptv.py
Traceback (most recent call last):
  File "iptv.py", line 4, in <module>
    import urllib2, urllib, google, sys, os, time , censys
  File "C:\Users\Ludo\Desktop\IPTV-dev-dev\iptv\censys.py", line 3, in <module>
    import requests
ImportError: No module named requests
```

With master version, when i attack a site, the script show this message:
`"Cannot open the current Language file. Try another one"﻿`

**Comment by pikomule** [comment]
I have the same problem: line 192, 145 and 141
